export { default as Slogan } from './Slogan';
export { default as Mailchimp } from './Mailchimp';
export { default as ScrollDown } from './ScrollDown';
export { default as GeneralParameters } from './GeneralParameters';
export { default as ContainerInfo } from './ContainerInfo';
export { default as WhitePill } from './WhitePill';
export { default as ImgVideo } from './ImgVideo';
export { default as FormMail } from './FormMail';
export { default as CustomTooltip } from './CustomTooltip';
