export { default as high } from './High.png'
export { default as highSelected } from './HighSelected.png'
export { default as medium } from './Medium.png'
export { default as mediumSelected } from './MediumSelected.png'
export { default as low } from './Low.png'
export { default as lowSelected } from './LowSelected.png'

export { default as one } from './Two.png'
export { default as oneSelected } from './TwoSelected.png'
export { default as two } from './Two.png'
export { default as twoSelected } from './TwoSelected.png'
export { default as three } from './Three.png'
export { default as threeSelected } from './ThreeSelected.png'
export { default as four } from './Four.png'
export { default as fourSelected } from './FourSelected.png'

export { default as square } from './Square.png'
export { default as squareSelected } from './SquareSelected.png'
export { default as rectangle } from './Rectangle.png'
export { default as rectangleSelected } from './RectangleSelected.png'
export { default as custom } from './Custom.png'
export { default as customSelected } from './CustomSelected.png'

export { default as steps1 } from './Steps1.png'

export { default as step1 } from './Step2.png'
export { default as step2 } from './Step2.png'
export { default as step3 } from './Step2.png'

export { default as vertical } from './Vertical.png'
export { default as verticalSelected } from './VerticalSelected.png'
export { default as horizontal } from './Horizontal.png'
export { default as horizontalSelected } from './HorizontalSelected.png'

export { default as regenIcon } from './Regen.png'

export { default as fifty } from './50.png'
export { default as fiftySelected } from './50Selected.png'
export { default as sixty } from './60.png'
export { default as sixtySelected } from './60Selected.png'
export { default as seventy } from './70.png'
export { default as seventySelected } from './70Selected.png'

export { default as smallFlat } from './SmallFlat.png'
export { default as smallFlatSelected } from './SmallFlatSelected.png'
export { default as mediumFlat } from './MediumFlat.png'
export { default as mediumFlatSelected } from './MediumFlatSelected.png'
export { default as largeFlat } from './LargeFlat.png'
export { default as largeFlatSelected } from './LargeFlatSelected.png'

export { default as close } from './Close.png'
export { default as closeSelected } from './CloseSelected.png'
export { default as open } from './Open.png'
export { default as openSelected } from './OpenSelected.png'
export { default as work } from './Work.png'
export { default as workSelected } from './WorkSelected.png'
